### ISSUE TITLE
annoying problem

### ISSUE THREAD

**Issue by subdesign** [possan/sublime_unicode_nbsp#16]
hey,
I very like this package, on saving removes all unvisible chars. 
but
when I enter characters, at specific places (like after => in arrays) it leaves an empty space which occurs an error for the linter, and I can't save the file. I have to go back always and delete this  - in the picture red - highlighted empty space.

check the uploaded screenshot:
<img width="385" alt="Screenshot 2020-06-25 at 10 34 39" src="https://user-images.githubusercontent.com/691695/85686124-fa2d9c00-b6cf-11ea-8ed2-f044d2906885.png">

I use Sublime 3.3.2 build3211
how to fix that? Am I the only person who struggle with this?
**If the highlighter only shows the unneeded char, what could put this extra char into my code?!?**
 
EDIT: anim gif how it behaves:
![Jun-25-2020 10-58-35](https://user-images.githubusercontent.com/691695/85689612-1252ea80-b6d3-11ea-8038-c117aadd11f8.gif)

**Comment by gardiner** [comment]
Hi @subdesign, what you are seeing is a protected/non-breaking space character. It is typed using `Alt-Space` and is often entered accidentally after or before typing a character that requires the ALT modifier (e.g. brackets or curly braces). PHP seems to tolerate this space in some places, but it is still a good idea to replace the character with a normal space. So if you are seeing this character, the plugin is doing its job and showing you something you would want to fix :)

**Comment by subdesign** [comment]
sorry I forgot to close this issue. it was a key combination in ST4 which put a non-visible char in the editor in my locale (hun) keyboard. now when I wait a sec after pressing this key combination (shift+alt+x enters char `>`) no extra char appear in the editor. it was discussed in the sublime discord, they also said it's a strange thing but it's solved.
