### ISSUE TITLE
The plugin is not available in packet manager for ST3

### ISSUE THREAD

**Issue by tristanbes** [possan/sublime_unicode_nbsp#8]
The plugin is not available in packet manager for ST3.

At least i can't find it. I couldn't install it manually either.

Any help please?

**Comment by tristanbes** [comment]
Installed it manually but weird cause it's isn't listed in the packages settings. Yet, still not listed in the packager control

**Comment by ream88** [comment]
@tristanbes how did you installed it manually? Does not work for me at all :/

**Comment by ream88** [comment]
@tristanbes forget it, installed it into `Installed Packages` instead of `Packages`… Silly me!

**Comment by nunofgs** [comment]
This plugin is now available in the Package Manager for ST3.

**Comment by possan** [comment]
Awesome, thanks.

**Comment by tristanbes** [comment]
Thanks.
